#!/bin/bash

# GeneInsight Platform - Render.com Deployment Script
# This script helps deploy to Render.com with full LangChain support

echo "🎨 GeneInsight Platform - Render.com Deployment"
echo "==============================================="

echo "📋 Deployment Steps:"
echo "1. Fork this repository on GitHub"
echo "2. Go to https://render.com and sign up"
echo "3. Connect your GitHub account"
echo "4. Create new 'Web Service' from your forked repo"
echo "5. Use these settings:"
echo ""
echo "   Build Command: cd ml_service && pip install -r requirements.txt && pip install transformers torch langchain-community"
echo "   Start Command: cd ml_service && python app.py"
echo "   Environment: Python 3.9"
echo ""
echo "6. Add environment variables:"
echo "   FLASK_ENV=production"
echo "   TRANSFORMERS_CACHE=/opt/render/project/src/transformers_cache"
echo "   PORT=5000"
echo ""
echo "7. Create PostgreSQL database service"
echo "8. Connect database to web service"
echo ""
echo "✅ Your app will be available at: https://your-app.onrender.com"
echo "🧠 Full LangChain features will work!"
echo "💬 AI Chat: https://your-app.onrender.com/ai-chat"
echo ""
echo "📊 Monitor deployment:"
echo "   - Check Render dashboard for logs"
echo "   - First deployment takes ~5-10 minutes (model download)"
echo "   - Subsequent deployments are faster"
echo ""
echo "🔧 Troubleshooting:"
echo "   - If build fails, check Python version (use 3.9)"
echo "   - If memory issues, upgrade to paid plan"
echo "   - Check logs for specific error messages"
